### PR TITLE
Update README for the CRI-O integration

### LINKED ISSUE #1: Broken link in doc
The link for 'Simple Wasi Application' is broken.

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
In the `docs/examples/simple_wasi_app.md` file, you have the following line:

```
sudo crictl create $POD_ID container_nbody.json sandbox_config.json
```

The `container_nbody.json` file was not mentioned before in the docs? Thanks.

**Comment by hydai** [comment]
> In the `docs/examples/simple_wasi_app.md` file, you have the following line:
> 
> ```
> sudo crictl create $POD_ID container_nbody.json sandbox_config.json
> ```
> 
> The `container_nbody.json` file was not mentioned before in the docs? Thanks.

Fixed.

**Comment by juntao** [comment]
The README doc and simple wasi doc has some overlaps. I think overlaps are generally undesirable since they could get out of sync over time.

I think we could remove the content in the simple wasi doc after publishing the Docker image.  And ask the reader to go back to the main README to continue CRI-O operations.

**Comment by hydai** [comment]
Cool. I've removed the redundant part. Please check. Thanks.

**Review by juntao — APPROVED** [review]
I added a ToC to README. I think this looks good now.

**Comment by juntao** [comment]
I think we can merge. Tim went through the instructions and made a video.

https://youtu.be/lr4LsOnqaLY

Next step is to complete the k8s section. ;)

**Comment by hydai** [comment]
Sure, I've also updated the youtube link in README.

**Pull request merged**
